name: Run Python script

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: 'Invoke API unconditionally'
        type: boolean
        required: true
        default: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: python 邮箱.py
